### ISSUE TITLE
Excellent work

### ISSUE THREAD

**Issue by Michlong** [daweileng/Precise-CTC#1]
I am using lstm+ctc with keras, too. Same problems are met, like you mentioned. Some theano based ctc implementations cannot ouput reliable loss and the weights are not convergent. Well, you seem to find the nidus, I will try you implementations in my work. 
By the way, this issue is not for 'issue', just for a comment. Thanks for your work. Are you Chinese?

**Comment by daweileng** [comment]
@Michlong : Thanks for the comment. I'll be glad to hear if my code helps, and any issue will be welcome.
